### ISSUE TITLE
[staging] Erro no admin de Obras

### ISSUE THREAD

**Issue by hgodinho** [hgodinho/wiki-ema#11]
Erro no admin de Obras

```
O site está passando por dificuldades técnicas. Verifique a caixa de entrada do e-mail do administrador do site para obter instruções.


Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /home/emaklgcm/public_html/site/staging/wp-content/plugins/wiki-ema/acervo.php:517
Stack trace:
#0 /home/emaklgcm/public_html/site/staging/wp-includes/class-wp-hook.php(288): Acervo_Emak->wiki_ema_custom_columns('az')
#1 /home/emaklgcm/public_html/site/staging/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/emaklgcm/public_html/site/staging/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-posts-list-table.php(1257): do_action('manage_obras_po...', 'az', 128312)
#4 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-list-table.php(1332): WP_Posts_List_Table->column_default(Object(WP_Post), 'az')
#5 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-posts-list-table.php(1290): WP_List_Table->single_row_columns(Object(WP_Post))
#6 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-posts-list-table.p in /home/emaklgcm/public_html/site/staging/wp-content/plugins/wiki-ema/acervo.php on line 517
1 - Uncaught Error: Cannot use object of type WP_Error as array in /home/emaklgcm/public_html/site/staging/wp-content/plugins/wiki-ema/acervo.php:517 Stack trace: #0 /home/emaklgcm/public_html/site/staging/wp-includes/class-wp-hook.php(288): Acervo_Emak->wiki_ema_custom_columns('az') #1 /home/emaklgcm/public_html/site/staging/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home/emaklgcm/public_html/site/staging/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-posts-list-table.php(1257): do_action('manage_obras_po...', 'az', 128312) #4 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-list-table.php(1332): WP_Posts_List_Table->column_default(Object(WP_Post), 'az') #5 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-posts-list-table.php(1290): WP_List_Table->single_row_columns(Object(WP_Post)) #6 /home/emaklgcm/public_html/site/staging/wp-admin/includes/class-wp-posts-list-table.p - /home/emaklgcm/public_html/site/staging/wp-content/plugins/wiki-ema/acervo.php - 517
```

**Comment by hgodinho** [comment]
esse erro acontece porque estou usando o plugin Multiple Themes. Enquanto o tema principal ativo for o Bridge, esse problema persistirá. Quando mudo para o Wiki-Ema, o problema some. 

Solução:

Criar uma instalação exclusiva do Wordpress para a Wiki-ema. Isso vai resultar em diversas atualizações tanto no plugin quanto no tema para gerar uma compatibilidade com essa modificação.

**Comment by hgodinho** [comment]
Instalação independente criada e esse problema não existe mais
